export const RESET_PASSWORD_TEXT = {
  TITLE: 'Set new password',
  LINKED_TOKEN_SUBTITLE: 'Choose a new password for your account.',
  MANUAL_TOKEN_SUBTITLE: 'Open the reset link from your email or paste your token below.',
  EMAIL_LABEL: 'Email address',
  EMAIL_PLACEHOLDER: 'you@example.com',
  TOKEN_LABEL: 'Reset token',
  TOKEN_PLACEHOLDER: 'Paste token from your email',
  NEW_PASSWORD_LABEL: 'New password',
  NEW_PASSWORD_PLACEHOLDER: 'Min. 8 characters',
  CONFIRM_PASSWORD_LABEL: 'Confirm new password',
  CONFIRM_PASSWORD_PLACEHOLDER: 'Repeat your new password',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match.',
  RESET_FAILED: 'Something went wrong. Please try again.',
  RESET_SUCCESS: 'Password reset successfully. You can now sign in.',
  RESET_BUTTON: 'Reset password',
  RESETTING_BUTTON: 'Resetting…',
  BACK_TO_SIGN_IN: 'Back to sign in',
} as const;
