export const ADMIN_USER_DETAIL_TEXT = {
  TITLE: 'User details',
  SUBTITLE: 'Inspect profile metadata, change role, and apply delete actions.',
  LOADING: 'Loading…',
  NOT_FOUND: 'User not found.',
  BACK_TO_USERS: '← Back to users',
  CATEGORY: 'Category',
  LEVEL: 'Level',
  NOT_SET: 'Not set',
  DIFFICULTY: 'Difficulty',
  SESSIONS: 'Sessions',
  JOINED: 'Joined',
  STATUS: 'Status',
  DELETED: 'Deleted',
  ACTIVE: 'Active',
  ASSIGN_ROLE: 'Assign role',
  SAVE_ROLE: 'Save role',
  SAVING_ROLE: 'Saving…',
  DANGER_ZONE: 'Danger zone',
  SOFT_DELETE_WARNING: 'Soft-delete this user. Their data will be retained.',
  DELETE_USER: 'Delete user',
  DELETING_USER: 'Deleting…',
  CONFIRM_DELETE_MESSAGE: (email: string) => `Soft-delete ${email}? They can still be restored.`,
  CONFIRM_DELETE_TITLE: 'Confirm user deletion',
  CONFIRM_DELETE_BUTTON: 'Delete user',
  ROLE_UPDATED: 'Role updated.',
  ROLE_UPDATE_FAILED: 'Failed to update role.',
  USER_DELETED: 'User deleted.',
  USER_DELETE_FAILED: 'Failed to delete user.',
} as const;
