import type { RegisterStep } from './RegisterTypes';

export const REGISTER_STEPS: RegisterStep[] = ['info', 'preferences', 'verify'];

export const REGISTER_TEXT = {
  INFO_TITLE: 'Create account',
  INFO_SUBTITLE: 'Join thousands of developers preparing for interviews',
  PREFERENCES_TITLE: 'Your focus area',
  PREFERENCES_SUBTITLE: 'Help us tailor your experience',
  VERIFY_TITLE: 'Verify your email',
  GOOGLE_SIGN_UP: 'Sign up with Google',
  EMAIL_DIVIDER: 'or continue with email',
  FIRST_NAME: 'First name',
  LAST_NAME: 'Last name',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  FIRST_NAME_PLACEHOLDER: 'John',
  LAST_NAME_PLACEHOLDER: 'Doe',
  EMAIL_PLACEHOLDER: 'you@example.com',
  PASSWORD_PLACEHOLDER: 'Min. 8 characters',
  CONTINUE: 'Continue →',
  TECHNOLOGY_CATEGORY: 'Technology category',
  REQUIRED_MARK: '*',
  EXPERIENCE_LEVEL: 'Experience level',
  OPTIONAL_MARK: '(optional)',
  LOADING_OPTIONS: 'Loading options…',
  BACK: '← Back',
  CREATE_ACCOUNT: 'Create account',
  CREATING: 'Creating…',
  VERIFICATION_CODE: 'Verification code',
  VERIFICATION_PLACEHOLDER: '000000',
  VERIFY_EMAIL: 'Verify email',
  VERIFYING: 'Verifying…',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  SIGN_IN: 'Sign in',
  CATEGORY_REQUIRED: 'Please select a category.',
  REFERENCE_LOAD_FAILED: 'Failed to load reference data.',
  REGISTER_FAILED: 'Something went wrong. Please try again.',
  VERIFY_FAILED: 'Invalid code. Please try again.',
  VERIFY_SUCCESS: 'Account verified! You can now sign in.',
} as const;
