export const ADMIN_PENDING_QUESTIONS_TEXT = {
  TITLE: 'Pending questions',
  SUBTITLE: 'Approve, reject, and adjust tags before suggested questions become live.',
  NO_PENDING: "No pending questions. You're all caught up!",
  BY: 'by',
  UNKNOWN: 'Unknown',
  VIEW_DETAILS: 'View details',
  HIDE_DETAILS: 'Hide details',
  EXACT_QUESTION: 'Exact question',
  EXPECTED_ANSWER: 'Expected answer',
  TAGS: 'Tags',
  LOADING_DETAILS: 'Loading details…',
  FAILED_TO_LOAD_DETAILS: 'Failed to load details.',
  SAVE_TAGS: 'Save tags',
  SAVING_TAGS: 'Saving…',
  TAG_REQUIRED: 'At least one tag is required.',
  TAGS_UPDATED: 'Tags updated.',
  TAGS_UPDATE_FAILED: 'Failed to update tags.',
  APPROVE: 'Approve',
  REJECT: 'Reject',
  CONFIRM_REJECT: 'Confirm reject',
  REJECTING: 'Rejecting…',
  CANCEL: 'Cancel',
  REASON_PLACEHOLDER: 'Reason for rejection (optional)',
  QUESTION_APPROVED: 'Question approved.',
  QUESTION_APPROVE_FAILED: 'Failed to approve question.',
  QUESTION_REJECTED: 'Question rejected.',
  QUESTION_REJECT_FAILED: 'Failed to reject question.',
  FAILED_TO_LOAD_QUESTIONS: 'Failed to load pending questions.',
  FAILED_TO_LOAD_TAGS: 'Failed to load tags.',
} as const;
