export const QUESTION_DETAIL_TEXT = {
  LOAD_FAILED: 'Failed to load question.',
  NOT_FOUND: 'Question not found.',
  BACK_TO_QUESTIONS: '← Back to questions',
  QUESTIONS: '← Questions',
  DELETE_QUESTION: 'Delete question',
  DELETING: 'Deleting…',
  QUESTION_DELETED: 'Question deleted.',
  DELETE_FAILED: 'Failed to delete question.',
  REPHRASE_FAILED: 'Failed to rephrase question.',
  REPHRASING: 'Rephrasing…',
  REPHRASE_WITH_AI: 'Rephrase with AI',
  REPHRASE_AGAIN: 'Rephrase again',
  SHOW_ORIGINAL: 'Show original',
  AI_REPHRASED_VERSION: 'AI rephrased version',
  TRY_YOUR_ANSWER: 'Try your answer',
  ANSWER_PLACEHOLDER: 'Write your answer here, then run AI check...',
  CHECKING: 'Checking…',
  CHECK_WITH_AI: 'Check with AI',
  CLEAR_RESULT: 'Clear result',
  ACCURACY: 'Accuracy',
  CORRECTNESS: 'Correctness',
  COMPLETENESS: 'Completeness',
  AI_FEEDBACK: 'AI feedback',
  NO_FEEDBACK: 'No feedback returned.',
  SHOW_ANSWER: 'Show answer',
  HIDE_ANSWER: 'Hide answer',
  TAGS: 'Tags',
  DELETE_CONFIRM_MESSAGE: 'Delete this question?',
  DELETE_CONFIRM_TITLE: 'Confirm deletion',
  DELETE_CONFIRM_ACTION: 'Delete',
  ANSWER_REQUIRED: 'Please enter your answer first.',
  CHECK_FAILED: 'Failed to check answer.',
} as const;

export const QUESTION_DIFFICULTY_COLORS: Record<string, string> = {
  Easy: 'text-green-600 bg-green-50 border-green-100',
  Medium: 'text-yellow-600 bg-yellow-50 border-yellow-100',
  Hard: 'text-red-600 bg-red-50 border-red-100',
};
