export const PROFILE_TEXT = {
  TITLE: 'Profile',
  ACCOUNT_SECTION: 'Account',
  FOCUS_SECTION: 'Focus',
  FULL_NAME: 'Full name',
  EMAIL: 'Email address',
  ROLE: 'Role',
  MEMBER_SINCE: 'Member since',
  CATEGORY: 'Category',
  LEVEL: 'Level',
  NOT_SET: 'Not set',
  FIRST_NAME: 'First name',
  LAST_NAME: 'Last name',
  EDIT: 'Edit',
  SAVE: 'Save',
  SAVING: 'Saving…',
  CANCEL: 'Cancel',
  LOADING: 'Loading…',
  LOAD_FAILED: 'Failed to load profile.',
  PROFILE_LOAD_FAILED_TOAST: 'Failed to load profile.',
  SAVE_SUCCESS_TOAST: 'Saved successfully.',
  SAVE_FAILED_TOAST: 'Something went wrong.',
  EMPTY_VALUE: '—',
} as const;
